floyd/client/data.py, floyd/client/files.py, floyd/client/module.py, floyd/client/usage.py
A support for some new features in`.flyntignore`, known from `.gitignore` files. I know you guys are working on something much bigger, but maybe this can serve as a temporary solution (as I get quite a lot of questions about this on Slack).
Some examples:
```
*.dat
/some_folder/*.dat
/some_folder/**/*.dat
.DS_Store
/some_folder/.DS_Store
/some_folder/**/.DS_Store
/some_folder
/some_folder/
```
=> More complete .flyntignore file support

floyd/client/common.py, tests/client/common_test.py
Prior to this fix, client will crash with the following error under py2:
```
line 13, in get_url_contents
return response.content.decode()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1170: ordinal not in range(128)
```
You can try reproduce it with `floyd logs -t LbiFKtkCV7tZo4aaDtfYga `
=> fix(crash): decode server response with proper encoding

floyd/cli/experiment.py, setup.py, tests/cli/experiment/delete_test.py, tests/cli/experiment/mocks.py
I found myself wanting this feature, and then I noticed that it was requested a couple of times on the forum, too. Here are links to the posts:
[Deleting multiple experiments](https://forum.floydhub.com/t/deleting-multiple-experiments/)
[Delete experiments by name / Bulk delete experiments](https://forum.floydhub.com/t/delete-experiments-by-name-bulk-delete-experiments/95)
I noticed that a similar PR (#7)  was opened to enable this feature for deleting multiple data ids at the same time, but it was closed without any discussion. Is this a feature that you specifically do not want implemented? If so, some insight would be appreciated.
As suggested in the [Click documentation](http://click.pocoo.org/6/arguments/#variadic-arguments), I thought it would be best to allow no ids to be passed …
=> Allow delete command to accept multiple experiment ids

floyd/cli/data.py, floyd/client/base.py, floyd/client/data.py, floyd/exceptions.py, tests/cli/data/delete_test.py, tests/cli/data/mocks.py
If one of the ids fails to delete, this approach still attempts to delete the other ids, but will have an exit status of 1. This is similar to docker's `rmi` approach to image deletion.
I didn't notice this when making the changes in #14, but issues #17 and #18 got me thinking about how to start handling failed API calls and their associated log messages more gracefully. Fundamentally, log messages and exception handling for requests to the API are the responsibility of the Client class (DataClient in this case), so I moved those tasks over there in these changes. I noticed that we are doing some logging in some Client classes already ([here](https://github.com/floydhub/floyd-cli/blob/master/floyd/client/data.py#L49) for example). The re-usability and consistency that gives is nice, and …
=> Allow 'floyd data delete' to accept multiple ids

setup.py
Some `pip` versions will fail to install `floyd-cli` if the `--pre` flag isn't passed, since we rely on `backports.tempfile`, which [only has a 1.0rc1](https://pypi.python.org/simple/backports.tempfile/) release at the moment.
From the [pip docs](https://pip.pypa.io/en/stable/reference/pip_install/#pre-release-versions):
> Starting with v1.4, pip will only install stable versions as specified
> by PEP426 by default. If a version cannot be parsed as a compliant
> PEP426 version then it is assumed to be a pre-release.
> 
> If a Requirement specifier includes a pre-release or development version
> (e.g. >=0.0.dev0) then pip will allow pre-release and development
> versions for that requirement.
While the behaviors of different `pip` versions differ with regard to pre-release versions, [this …
=> Fix failing install with some pip versions

floyd/client/data.py
A leaked file descriptor will cause the following error in Windows:
PermissionError: [WinError 32] The process cannot access the file
because it is being used by another process
=> fix(crash): close data.gar file descriptor after upload

floyd/manager/floyd_ignore.py, tests/manager/floyd_ignore/get_lists_test.py
@houqp @narenst
I was updating the docs for floydignore logic to include the new changes released today and I discovered a bug that will affect many users:
Patterns starting with a `/` don't match directories.
We use [`PurePath.match()`](https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.match) to match glob patterns for .floydignore. Its docs state that a pattern with a preceding '/' will be interpreted as an absolute path and will only match against absolute paths.
By removing the `/` prefix when parsing the glob patterns, we get the desired matching behavior.
=> Remove / prefix on .floydignore patterns

.bumpversion.cfg, setup.py
retag cli for new release, previous version was deleted from pypi
=> Bump version: 0.9.8 → 0.9.9

floyd/client/base.py
The clone command downloads code and datasets. Sometimes these are very
large in size. Having a progress bar makes it easy to figure out how
long it will take to download the entire file.
=> Add progress bar for downloads

floyd/client/auth.py
Now that we are returning json for invalid token error the CLI
was throwing this error:
```
File "/Users/naren/Code/floyd/floyd-cli/floyd/model/user.py", line 14,
in make_user
return User(**data)
TypeError: __init__() missing 4 required positional arguments:
'uid', 'username', 'email', and 'type'
```
This was because the login client was not using the same base web client
as the other clients.
=> Regression: Handle invalid token error

floyd/cli/auth.py
Our check for `if not access_code:` wasn't really helping much. Click will automatically re-prompt if nothing was entered, and strings of whitespace are truthy in Python. This change brings us closer to the original intent of the check, I think.
=> strip whitespace from access_code on login

floyd/cli/run.py, tests/cli/run/test_run.py
I fiddled with this for a bit, and it seems like click doesn't allow a built-in way to do this. The solution I have here definitely works, even if a bit hacky.
Let me know if you want anything changed.
=> limit jobs to one --env

README.md, conda/meta.yaml
These changes will update clean up the anaconda page a bit. I haven't found a way to override the installation instructions :/
https://anaconda.org/mckayward/floyd-cli Shows how this will end up rendering
=> add readme as description

floyd/cli/experiment.py
When running `floyd logs`, if the job is currently in a queue, retry until the job is actually running (sleeping for one second between attempts).
=> floyd logs: automatically retry if queued

floyd/cli/data.py
My workflow involves setting off multiple runs with different parameters then examining TensorBoard results from each run. To support automating this, this commit adds `floyd data listfiles` (list all files in a particular dataset) and `floyd data getfile` (download a specific file from a dataset).
=> Add `floyd data listfiles` and `floyd data getfile` commands

floyd/cli/experiment.py, floyd/model/experiment.py
This adds a new column to the job status table with the latest values of job metrics:
```
$ floyd status
JOB NAME                                  CREATED     STATUS      DURATION(s)  INSTANCE    DESCRIPTION    METRICS
----------------------------------------  ----------  --------  -------------  ----------  -------------  ---------------------------------------------------------------------
floydlabs/projects/hot-dog-not-hot-dog/3  5 days ago  shutdown            519  c1                         {'val_loss': 0.0414, 'acc': 0.974, 'loss': 0.0897, 'val_acc': 0.9858}
floydlabs/projects/hot-dog-not-hot-dog/2  5 days ago  shutdown             53  c1
floydlabs/projects/hot-dog-not-hot-dog/1  5 days ago  success               3  c1
```
=> Add latest metrics value to job status

floyd/cli/run.py
Here's the output:
```bash
...
JOB NAME
-----------------------------
redeipirati/projects/deprecation/999
URL to job: https://www.floydhub.com/redeipirati/projects/deprecation/999
[!] DEPRECATION NOTICE
Jupyter mode will be no longer availble after September 15th.
We suggest you to upgrade your workflow by using FloydHub Workspaces: https://docs.floydhub.com/guides/workspace/.
```
=> Deprecation notice for Jupyter mode 

floyd/cli/utils.py
The data clone command should work without requiring a `floyd init`
=> Allow data clone without init

floyd/cli/data_upload_utils.py, floyd/client/files.py
- [catch permission denied error](https://app.asana.com/0/817307208669065/750539112198237)
- catch Ctrl-C signal during compression and purge tarball file.
I'm not sure about the location of the `warn_purge_exit` function, should it be defined inside the `create_tarfile` function since it will be used only in this context?
=> Catch permission and Ctrl-C signal during compression

floyd/cli/experiment.py
Ticket: [When using --follow from CLI, command doesn't exit when job is done](https://app.asana.com/0/817307208669065/811109963478542)
=> Exit on follow by inspecting the current log line

floyd/cli/utils.py
- [[cli] data init crash due to invalid input](https://app.asana.com/0/817307208669065/750539112198242)
E.g. 
```bash
(cli-venv) fh:tmp ReDeiPirati $ floyd data init /
Argument '/' doesn't match any recognized pattern:
floyd [data] init <project_or_dataset_name>
floyd [data] init <namespace>/<project_or_dataset_name>
floyd [data] init <namespace>/[projects|dataset]/<project_or_dataset_name>
Note: Argument can contains only alphanumeric and - chars
```
=> Catch bad arguments during `floyd [data] init`

floyd/cli/run.py, floyd/cli/utils.py, tests/cli/run/test_run.py
- [[cli] crash in processing data mount ids](https://app.asana.com/0/817307208669065/750539112198233)
```bash
(cli-venv) pirate:cli-test pirate$ floyd run --data https://www.floydhub.com/pirate/datasets/my-data:
Argument 'https://www.floydhub.com/pirate/datasets/my-data:' doesn't match any recognized pattern:
floyd run --data <dataset_name>
floyd run --data <dataset_name>:<mounting_point>
floyd run --data <namespace>/[projects|dataset]/<dataset_or_project_name>
floyd run --data <namespace>/[projects|dataset]/<dataset_or_project_name>
floyd run --data <namespace>/[projects|dataset]/<dataset_or_project_name>/<version>
floyd run --data <namespace>/[projects|dataset]/<dataset_or_project_name>/<version>:<mounting_point>
floyd run --data <data_id> (DEPRECATED)
floyd run --data …
```
=> Regex to catch bad data mount

.circleci/config.yml
separate out annaconda deployment so we can manually restart it in case of pypi issue.
=> separate pypi and annaconda deployments

floyd/client/data.py
- [`floyd data status` doesn't return the right output](https://app.asana.com/0/450555463829754/885556015345276)
=> Fix `floyd data status`

floyd/cli/data.py, floyd/cli/experiment.py, floyd/cli/run.py
Now it's possible to download a directory from a Job or dataset with the `floyd [data] clone --directory <dir_name> ID`
=> Feature Request: Download a directory inside the output using cli
