- floyd/client/data.py
- floyd/client/files.py
- floyd/client/module.py
- floyd/client/usage.py
- setup.py
...with support for older Python versions.
> Powerful flyntignore

- floyd/cli/auth.py
- floyd/cli/run.py
- floyd/client/auth.py
- floyd/client/module.py
- floyd/model/experiment.py
Point to documentation where appropriate
> Improve messaging in CLI

- floyd/log.py
> Log cli output to stdout

- floyd/development/local.py
> use 127.0.0.1 instead of localhost for local mode

- README.rst
* Updates install link
* Changes 'getting started' links to 'quick start' links
> Fix up a couple links in the README

- floyd/cli/data.py
- floyd/model/data.py
- floyd/model/resource.py
also fix output command for dataset.
> remove uri reference from cli

- floyd/cli/auth.py
- floyd/client/auth.py
- floyd/model/credentials.py
Uses the new login api in the backend.
> Username password login

- floyd/cli/run.py
> allow shortnames for floyd restart

- floyd/cli/auth.py
> prompt for password if flag not passed

- conda/meta.yaml
- setup.py
- tests/cli/version_test.py
> add tests for floyd upgrade

- conda/meta.yaml
- floyd/cli/version.py
- setup.py
So the upgrade command just prints the conda command to upgrade
> conda install is causing issues on win

- floyd/cli/experiment.py
> Add -f/--follow alias for -t/--tail cli flag

- floyd/client/base.py
> Caught requests.exceptions.Timeout exception class

- floyd/main.py
Bug Reported from Forum's user, [here](https://forum.floydhub.com/t/fyi-typo-error-in-floydhub-cli-update/768)
> Fixed typo: apend with append

- floyd/cli/version.py
fix https://github.com/floydhub/floyd-cli/issues/175
> avoid importing pip internal api

- floyd/cli/auth.py
Keep the `--token` option for backwards compatibility.
> Make username/pwd as default login option

- floyd/cli/experiment.py
- floyd/cli/run.py
- Redirect output command to `/files`
- Fix deprecation notice according to #198
> Fix floyd output command

- floyd/cli/auth.py
- floyd/cli/data.py
- floyd/cli/experiment.py
- floyd/cli/run.py
- floyd/cli/version.py
- floyd/main.py
- Use consistent terminology.
- Fix typos and any incorrect information.
> Update cli help text

- floyd/client/files.py
Ticket: [[cli] catch no disk space error](https://app.asana.com/0/817307208669065/750539112198235)
> Catch no space left

- floyd/cli/data_upload_utils.py
- floyd/client/base.py
Minor change so that programatic uploads and downloads can be controlled better.
> Configurable upload download dirs

- floyd/cli/run.py
```bash
(cli-venv) pirate:test pirate$ floyd run --data redeipirati/datasets/test-ds/1  --data redeipirati/datasets/test-ds/1  'python train.py'
Creating project run. Total upload size: 691.0B
Syncing code ...
[================================] 2293/2293 - 00:00:00
JOB NAME
-----------------------------
redeipirati/projects/test/999
URL to job: https://www.floydhub.com/redeipirati/projects/test/999
DATANAME                         MOUNTING DIRECTORY
------------------------------  --------------------
redeipirati/datasets/test-ds/1    /IamTheIDforYourData
redeipirati/datasets/test-ds/2    /input
To view logs enter:
floyd logs redeipirati/projects/test/999
```
> Show data info

- floyd/cli/run.py
- floyd/cli/utils.py
- tests/cli/utils_test.py
Edited regex and test to reflect this.
> Fix regex: username can contains dots
